/**
 * Load unique AI copy JSON generated by the Vault AI Copy Factory.
 * Files live in frontend/data/ai-copy/{kind}/{slug}.json
 */
import fs from 'fs';
import path from 'path';

export type AiCopySection = { h2: string; paragraphs: string[] };
export type AiFaq = { q: string; a: string };
export type AiCopyLink = { href: string; anchor: string };

export type AiCopy = {
  site: string;
  kind: string;
  slug: string;
  overlayTarget?: string;
  canonicalPath: string;
  title: string;
  metaDescription: string;
  h1: string;
  lede: string;
  sections: AiCopySection[];
  faqs: AiFaq[];
  takeaways: string[];
  internalLinks: AiCopyLink[];
  sourceNote: string;
};

const COPY_DIR: string = (() => {
  const override = process.env.AI_COPY_DIR;
  if (override) return override;
  return path.join(process.cwd(), 'data', 'ai-copy');
})();

type IndexFile = {
  overlayIndex: Record<string, { kind: string; slug: string }>;
  slugIndex: Record<string, { kind: string; overlayTarget?: string; canonicalPath?: string }>;
};

let indexMemo: IndexFile | null | undefined;
const fileMemo = new Map<string, AiCopy | null>();

function readJson<T>(full: string): T | null {
  try {
    return JSON.parse(fs.readFileSync(full, 'utf8')) as T;
  } catch {
    return null;
  }
}

function loadIndex(): IndexFile {
  if (indexMemo !== undefined) return indexMemo || { overlayIndex: {}, slugIndex: {} };
  const overlayIndex: IndexFile['overlayIndex'] = {};
  const slugIndex: IndexFile['slugIndex'] = {};
  if (fs.existsSync(COPY_DIR)) {
    for (const kind of fs.readdirSync(COPY_DIR, { withFileTypes: true })) {
      if (!kind.isDirectory()) continue;
      const dir = path.join(COPY_DIR, kind.name);
      for (const f of fs.readdirSync(dir)) {
        if (!f.endsWith('.json')) continue;
        const copy = readJson<AiCopy>(path.join(dir, f));
        if (!copy?.slug) continue;
        slugIndex[copy.slug] = {
          kind: copy.kind || kind.name,
          overlayTarget: copy.overlayTarget,
          canonicalPath: copy.canonicalPath,
        };
        if (copy.overlayTarget) overlayIndex[copy.overlayTarget] = { kind: copy.kind || kind.name, slug: copy.slug };
      }
    }
  }
  indexMemo = { overlayIndex, slugIndex };
  return indexMemo;
}

export const TIE_KINDS = new Set([
  'state-agency',
  'state-program',
  'state-industry',
  'occ-state',
  'industry-cycle',
  'industry-pac',
  'occ-cycle',
  'city-industry',
  'city-cycle',
  'occ-pac',
  'fec-vs-spend',
  'type-compare',
  'month-compare',
  'party-state',
  'party-cycle',
  'city-pac',
]);

export function isTieKind(kind: string): boolean {
  return TIE_KINDS.has(kind) || kind.startsWith('tie-');
}

export function listAiCopy(): Array<{ kind: string; slug: string }> {
  const idx = loadIndex();
  return Object.entries(idx.slugIndex).map(([slug, v]) => ({ kind: v.kind, slug }));
}

export function listTieCopy(): Array<{ kind: string; slug: string }> {
  return listAiCopy().filter((x) => isTieKind(x.kind));
}

export function listGuideCopy(): Array<{ kind: string; slug: string }> {
  return listAiCopy().filter((x) => !isTieKind(x.kind));
}

export function loadAiCopy(kind: string, slug: string): AiCopy | null {
  const key = `${kind}/${slug}`;
  if (fileMemo.has(key)) return fileMemo.get(key) ?? null;
  const copy = readJson<AiCopy>(path.join(COPY_DIR, kind, `${slug}.json`));
  fileMemo.set(key, copy);
  return copy;
}

export function loadAiCopyBySlug(slug: string): AiCopy | null {
  const hit = loadIndex().slugIndex[slug];
  if (!hit) return null;
  return loadAiCopy(hit.kind, slug);
}

export function loadOverlay(pathname: string): AiCopy | null {
  const normalized = pathname.endsWith('/') ? pathname : `${pathname}/`;
  const hit = loadIndex().overlayIndex[normalized];
  if (!hit) return null;
  return loadAiCopy(hit.kind, hit.slug);
}

function hrefMatches(href: string, pathname: string): boolean {
  if (!href || href.startsWith('http')) return false;
  const h = href.endsWith('/') ? href : `${href}/`;
  return h === pathname || (pathname !== '/' && h.startsWith(pathname));
}

export function listRelatedTies(pathname: string, limit = 8): AiCopy[] {
  const n = pathname.endsWith('/') ? pathname : `${pathname}/`;
  const exact: AiCopy[] = [];
  const related: AiCopy[] = [];
  for (const item of listTieCopy()) {
    const copy = loadAiCopyBySlug(item.slug);
    if (!copy) continue;
    if (copy.overlayTarget === n) {
      exact.push(copy);
      continue;
    }
    const overlayHit = Boolean(copy.overlayTarget && n !== '/' && copy.overlayTarget.startsWith(n));
    const linkHit = (copy.internalLinks || []).some((l) => hrefMatches(l.href, n));
    if (overlayHit || linkHit) related.push(copy);
  }
  const seen = new Set<string>();
  const out: AiCopy[] = [];
  for (const copy of [...exact, ...related]) {
    if (seen.has(copy.slug)) continue;
    seen.add(copy.slug);
    out.push(copy);
    if (out.length >= limit) break;
  }
  return out;
}
