/** Auto-generated by generate-gsc-popular-links.mjs — do not edit */
export default {
  "generatedAt": "2026-06-10T22:54:34.416Z",
  "siteId": "blackvaultdocs",
  "popularPages": [
    {
      "path": "/",
      "impressions": 33,
      "clicks": 0,
      "ctr": 0,
      "position": 17.272727272727273
    },
    {
      "path": "/blog/data-anomaly-a-jfk-assassination-file-emerges-in-nara-s-latest-mlk-declassification-batch-9536/",
      "impressions": 14,
      "clicks": 0,
      "ctr": 0,
      "position": 6.285714285714286
    },
    {
      "path": "/blog/doj-oig-2024-bop-special-housing-unit-concerns/",
      "impressions": 25,
      "clicks": 0,
      "ctr": 0,
      "position": 6.56
    },
    {
      "path": "/blog/doj-oig-fbi-oversight-misconduct-dna-nsa-2007-2025/",
      "impressions": 17,
      "clicks": 0,
      "ctr": 0,
      "position": 4.352941176470589
    },
    {
      "path": "/documents/doj-oig-audit-assets-forfeiture-fund-and-seized-asset-deposit-fund-annual-financial-statements-9/",
      "impressions": 10,
      "clicks": 0,
      "ctr": 0,
      "position": 11.9
    }
  ],
  "popularQueries": [
    {
      "query": "\"104-10250-10280\"",
      "impressions": 13,
      "position": 2.9230769230769234
    },
    {
      "query": "\"104-10250-10280\" \"hidalgo\" \"balmes\"",
      "impressions": 1,
      "position": 4
    },
    {
      "query": "\"104-10250-10280\" hidalgo balmes",
      "impressions": 6,
      "position": 1
    },
    {
      "query": "\"119-10021-10413\"",
      "impressions": 1,
      "position": 5
    },
    {
      "query": "\"198-10007-10021\"",
      "impressions": 3,
      "position": 6.333333333333333
    },
    {
      "query": "\"198-10007-10021\" pdf",
      "impressions": 3,
      "position": 8
    },
    {
      "query": "\"archives records 2023\" \"session 104\"",
      "impressions": 1,
      "position": 5
    },
    {
      "query": "\"grant governance\" or \"grant oversight\" best practices guidelines",
      "impressions": 6,
      "position": 4.666666666666666
    },
    {
      "query": "\"hidalgo, balmes\"",
      "impressions": 4,
      "position": 8.75
    },
    {
      "query": "\"hidalgo, balmes\" memorandum",
      "impressions": 3,
      "position": 8
    },
    {
      "query": "\"lionion\" cia",
      "impressions": 2,
      "position": 3
    },
    {
      "query": "\"report for july-august on actions taken to combat castro-communist subversion\"",
      "impressions": 4,
      "position": 2
    }
  ]
} as const;
