/** Auto-generated by generate-gsc-popular-links.mjs — do not edit */
export default {
  "generatedAt": "2026-06-10T18:45:49.129Z",
  "siteId": "blackvaultdocs",
  "popularPages": [
    {
      "path": "/",
      "impressions": 33,
      "clicks": 0,
      "ctr": 0,
      "position": 17.272727272727273
    },
    {
      "path": "/blog/data-anomaly-a-jfk-assassination-file-emerges-in-nara-s-latest-mlk-declassification-batch-9536/",
      "impressions": 14,
      "clicks": 0,
      "ctr": 0,
      "position": 6.285714285714286
    },
    {
      "path": "/blog/doj-oig-2024-bop-special-housing-unit-concerns/",
      "impressions": 25,
      "clicks": 0,
      "ctr": 0,
      "position": 6.56
    },
    {
      "path": "/blog/doj-oig-fbi-oversight-misconduct-dna-nsa-2007-2025/",
      "impressions": 17,
      "clicks": 0,
      "ctr": 0,
      "position": 4.352941176470589
    },
    {
      "path": "/documents/doj-oig-audit-assets-forfeiture-fund-and-seized-asset-deposit-fund-annual-financial-statements-9/",
      "impressions": 10,
      "clicks": 0,
      "ctr": 0,
      "position": 11.9
    }
  ],
  "popularQueries": [
    {
      "query": "\"198-10007-10021\" pdf",
      "impressions": 3,
      "position": 8
    },
    {
      "query": "\"hidalgo, balmes\"",
      "impressions": 4,
      "position": 8.75
    },
    {
      "query": "\"hidalgo, balmes\" memorandum",
      "impressions": 3,
      "position": 8
    },
    {
      "query": "\"report for july-august\" \"castro-communist\"",
      "impressions": 4,
      "position": 9
    },
    {
      "query": "2023 release government records reconstruction-era politics lincoln assassination archives",
      "impressions": 3,
      "position": 8.333333333333332
    }
  ]
} as const;
