/** Auto-generated by generate-gsc-popular-links.mjs — do not edit */
export default {
  "generatedAt": "2026-06-10T17:52:37.463Z",
  "siteId": "blackvaultdocs",
  "popularPages": [
    {
      "path": "/",
      "impressions": 170,
      "clicks": 1,
      "ctr": 0.0058823529411764705,
      "position": 6.970588235294118
    },
    {
      "path": "/about/",
      "impressions": 10,
      "clicks": 0,
      "ctr": 0,
      "position": 17.2
    },
    {
      "path": "/blog/data-anomaly-a-jfk-assassination-file-emerges-in-nara-s-latest-mlk-declassification-batch-9536/",
      "impressions": 15,
      "clicks": 0,
      "ctr": 0,
      "position": 6.866666666666666
    },
    {
      "path": "/blog/data-anomaly-look-at-the-5-most-recently-ingested-declassified-nara-foia-documents-2140/",
      "impressions": 12,
      "clicks": 0,
      "ctr": 0,
      "position": 6.833333333333333
    },
    {
      "path": "/blog/doj-oig-2024-bop-special-housing-unit-concerns/",
      "impressions": 143,
      "clicks": 0,
      "ctr": 0,
      "position": 7.6923076923076925
    },
    {
      "path": "/blog/doj-oig-fbi-oversight-misconduct-dna-nsa-2007-2025/",
      "impressions": 151,
      "clicks": 0,
      "ctr": 0,
      "position": 7
    }
  ],
  "popularQueries": [
    {
      "query": "\"archives*records 2023\" \"session 104\"",
      "impressions": 11,
      "position": 8.09090909090909
    },
    {
      "query": "\"hidalgo, balmes\"",
      "impressions": 17,
      "position": 9
    },
    {
      "query": "\"report for july-august on actions taken\" 1963",
      "impressions": 27,
      "position": 8.148148148148149
    },
    {
      "query": "\"report for july-august\" \"castro-communist\"",
      "impressions": 537,
      "position": 9.988826815642458
    },
    {
      "query": "\"report for july-august\" \"castro-communist\" 1963",
      "impressions": 29,
      "position": 10.241379310344827
    },
    {
      "query": "\"report for july-august\" actions taken to combat castro-communist subversion",
      "impressions": 11,
      "position": 8.818181818181818
    },
    {
      "query": "\"report for july-august\" castro-communist subversion",
      "impressions": 124,
      "position": 8.951612903225806
    }
  ]
} as const;
